### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by notedit** [notedit/media-server-go#36]
Undefined symbols for architecture x86_64:
  "_srtp_crypto_policy_set_aes_gcm_128_16_auth", referenced from:
      SRTPSession::Setup(char const*, unsigned char const*, unsigned long) in libmediaserver.a(SRTPSession.o)
  "_srtp_crypto_policy_set_aes_gcm_256_16_auth", referenced from:
      SRTPSession::Setup(char const*, unsigned char const*, unsigned long) in libmediaserver.a(SRTPSession.o)
ld: symbol(s) not found for architecture x86_64

**Comment by tombaki** [comment]
Undefined symbols for architecture x86_64:
  "_srtp_crypto_policy_set_aes_gcm_128_16_auth", referenced from:
      RTPTransport::SetLocalCryptoSDES(char const*, unsigned char const*, unsigned int) in libmediaserver.a(RTPTransport.o)
      RTPTransport::SetRemoteCryptoSDES(char const*, unsigned char const*, unsigned int) in libmediaserver.a(RTPTransport.o)
      SRTPSession::Setup(char const*, unsigned char const*, unsigned long) in libmediaserver.a(SRTPSession.o)
  "_srtp_crypto_policy_set_aes_gcm_256_16_auth", referenced from:
      RTPTransport::SetLocalCryptoSDES(char const*, unsigned char const*, unsigned int) in libmediaserver.a(RTPTransport.o)
      RTPTransport::SetRemoteCryptoSDES(char const*, unsigned char const*, unsigned int) in libmediaserver.a(RTPTransport.o)
      SRTPSession::Setup(char const*, unsigned char const*, unsigned long) in libmediaserver.a(SRTPSession.o)
ld: symbol(s) not found for architecture x86_64 
same issue on mac
