### ISSUE TITLE
go media-server-go lib build failed on ubuntu 16.04 x64

### ISSUE THREAD

**Issue by noxlesh** [notedit/media-server-go#40]
after successfull installation of native libs installation of media-server-go fails with:

```
# github.com/notedit/media-server-go/wrapper
/tmp/go-build087762447/b057/_x004.o: In function `RTPSessionFacade::Enqueue(std::shared_ptr<RTPPacket> const&)':
go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:462: undefined reference to `RTPSession::SendPacket(RTPPacket&)'
go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:462: undefined reference to `RTPSession::SendPacket(RTPPacket&)'
/tmp/go-build087762447/b057/_x004.o: In function `RawRTPSessionFacade::onRTPPacket(unsigned char*, int)':
go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:760: undefined reference to `RTPPacket::SetPayload(unsigned char const*, unsigned int)'
collect2: error: ld returned 1 exit status 
```

**Comment by minhtien2805** [comment]
Me too :(

**Comment by notedit** [comment]
I will give a look.

**Comment by notedit** [comment]
> Me too :( With CentOS

never try this on CentOS yet.

**Comment by AlexanderKozhevin** [comment]
I think I'm getting the same error on Ubuntu 16.04

```
# github.com/notedit/media-server-go/wrapper
/tmp/go-build024533421/b057/_x004.o: In function `RTPSessionFacade::Enqueue(std::shared_ptr<RTPPacket> const&)':
../go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:462: undefined reference to `RTPSession::SendPacket(RTPPacket&)'
../go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:462: undefined reference to `RTPSession::SendPacket(RTPPacket&)'
/tmp/go-build024533421/b057/_x004.o: In function `RawRTPSessionFacade::onRTPPacket(unsigned char*, int)':
../go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:760: undefined reference to `RTPPacket::SetPayload(unsigned char const*, unsigned int)'
collect2: error: ld returned 1 exit status
```

**Comment by AlexanderKozhevin** [comment]
Same thing on Ubuntu 18.04
```
/tmp/go-build762070801/b055/_x004.o: In function `_wrap_RTPSessionFacade_Enqueue_native_a625d9984f014aad':
../go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:462: undefined reference to `RTPSession::SendPacket(RTPPacket&)'
/tmp/go-build762070801/b055/_x004.o: In function `RTPSessionFacade::Enqueue(std::shared_ptr<RTPPacket> const&)':
../go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:462: undefined reference to `RTPSession::SendPacket(RTPPacket&)'
/tmp/go-build762070801/b055/_x004.o: In function `RawRTPSessionFacade::onRTPPacket(unsigned char*, int)':
../go/src/github.com/notedit/media-server-go/wrapper/mediaserver_wrap.cxx:760: undefined reference to `RTPPacket::SetPayload(unsigned char const*, unsigned int)'
collect2: error: ld returned 1 exit status

```

**Comment by notedit** [comment]
OK,  thanks for reporting.   I just  update the  c++ native code a few days ago.  I will fix this tomorrow.

**Comment by notedit** [comment]
@AlexanderKozhevin @minhtien2805  Can you test the merge-latest branch? 

the media-server-go and media-server-go-native  on the merge-latest branch meantime.

**Comment by notedit** [comment]
In my local test,  It fix this.

**Comment by noxlesh** [comment]
i rebuilded libs from merge-latest and then checked out media-server-go to merge-latest and go install  failed with:
`# github.com/notedit/media-server-go/wrapper
/tmp/go-build728828675/b057/_x004.o: In function `_wrap_DTLSICETransport_DumpBWEStats_native_33e841c002a314c3':
wrapper/mediaserver_wrap.cxx:5870: undefined reference to `DTLSICETransport::DumpBWEStats(char const*)'
collect2: error: ld returned 1 exit status
`

**Comment by notedit** [comment]
I  can not  reproduce  your issuse.   the travis-ci  build  on  unbutu 16.4, works fine.  

 https://travis-ci.org/notedit/media-server-go/jobs/549691925

**Comment by minhtien2805** [comment]
Me too 

go run webrtc-to-rtmp/server.go 
# github.com/notedit/media-server-go/wrapper
/tmp/go-build590121127/b128/_x004.o: In function `_wrap_DTLSICETransport_DumpBWEStats_native_33e841c002a314c3':
../media-server-go/wrapper/mediaserver_wrap.cxx:5841: undefined reference to `DTLSICETransport::DumpBWEStats(char const*)'
collect2: error: ld returned 1 exit status


root@21ff335f4316:/var/local/media-server-go/wrapper# swig -go -cgo -c++ -intgosize 64 mediaserver.i
../include/media-server/include/media.h:20: Warning 325: Nested class not currently supported (Listener ignored)
../include/media-server/include/media.h:59: Warning 325: Nested class not currently supported (RtpPacketization ignored)
mediaserver.i:1077: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
mediaserver.i:1118: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
../include/media-server/include/config.h:132: Warning 401: Nothing known about base class 'std::map< std::string,std::string >'. Ignored.
../include/media-server/include/config.h:132: Warning 401: Maybe you forgot to instantiate 'std::map< std::string,std::string >' using %template.
mediaserver.i:1002: Warning 401: Nothing known about base class 'std::vector< LayerSource * >'. Ignored.
mediaserver.i:1002: Warning 401: Maybe you forgot to instantiate 'std::vector< LayerSource * >' using %template.
mediaserver.i:1347: Warning 402: Base class 'MediaFrame::Listener' is incomplete.
../include/media-server/include/media.h:20: Warning 402: Only forward declaration 'MediaFrame::Listener' was found.
mediaserver.i:1409: Warning 401: Nothing known about base class 'RemoteRateEstimator::Listener'. Ignored.
../include/media-server/include/config.h:394: Warning 516: Overloaded method ByteBuffer::ByteBuffer(ByteBuffer const &) ignored,
../include/media-server/include/config.h:382: Warning 516: using ByteBuffer::ByteBuffer(ByteBuffer const *) instead.

**Comment by notedit** [comment]
please test the master brunch.  

I test the master branch on a fresh ubuntu 16.04.  It builds and works fine.

**Comment by AlexanderKozhevin** [comment]
@notedit 
I'm getting an error when run webrtc -> rtmp 

```
(index):70 WebSocket connection to 'ws://localhost:8000/channel' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ (index):70
onload @ (index):115
```

![Screenshot 2019-06-25 at 16 48 19](https://user-images.githubusercontent.com/4464561/60104007-46669900-9769-11e9-8df5-06ed64f7def0.png)

**Comment by notedit** [comment]
@AlexanderKozhevin  You should change your websocket url

**Comment by AlexanderKozhevin** [comment]
Oh, sorry. sure

**Comment by AlexanderKozhevin** [comment]
Is it critical issue?

```
[0x7fd332317700][1561471357.412][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[0x7fd331b16700][1561471359.412][DBG]-DTLSICETransport::SendPLI() | [ssrc:1636136717]
[0x7fd332317700][1561471359.412][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[0x7fd331b16700][1561471361.412][DBG]-DTLSICETransport::SendPLI() | [ssrc:1636136717]
[0x7fd332317700][1561471361.412][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet

```

**Comment by notedit** [comment]
check your endpoint settings

**Comment by AlexanderKozhevin** [comment]
@notedit When you tested on Ubuntu,  was it local machine?
I got semi- working webrtc -> rtmp on localhost . 
But getting error, when I deploy on server with domain attached with https.
```
[0x7f2572d4c700][1561744252.114][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
```
