### ISSUE TITLE
how to handle reconnectivity issue

### ISSUE THREAD

**Issue by syedMSohaib** [notedit/media-server-go#47]
How to handle the situation when the stream disconnects and should reconnect.  Basically, what I want to do  is wait 20 seconds after the initial disconnect, if the stream reconnects then it will resume as it is else it will stop and prompt user to create a new one.

So basically i need pause or resume functionality

**Comment by notedit** [comment]
You don't need pause or resume function,  you can just create a new IncomingStream,  and reattach the new IncomingStream.

**Comment by syedMSohaib** [comment]
So am i going to reattach the new IncomingStream via FFMPEG ?!  and one more thing what if we want to perform seeking because i've seen many live stream player where it give you an option to view the live feed and also recorded stream too simultaneously  so how am i going to do in case of reattachment (like Youtube)
