### ISSUE TITLE
Manually write video packets to outgoing stream

### ISSUE THREAD

**Issue by niklaskorz** [notedit/media-server-go#50]
There currently does not seem to be a way to directly write data to an outgoing stream track, similar to the `OnMediaFrame` callback of the ingoing stream track.
Is there a possibility to add something like a `WriteMediaFrame` method?

**Comment by niklaskorz** [comment]
The only possible way right now seems to be the streamer session which opens a UDP socket. But since I already have the data as a byte array in my Go code, I'd like to avoid this extra step.

**Comment by notedit** [comment]
@niklaskorz   I am working on this  on mediaframe-bridge.  It does not work yet.

**Comment by notedit** [comment]
https://github.com/notedit/media-server-go/blob/master/mediaframesession.go#L57

you can  write rtp data now.
