### ISSUE TITLE
fatal error: runtime.SetFinalizer: first argument is native.SwigcptrRTPIncomingSourceGroup, not pointer

### ISSUE THREAD

**Issue by benpeterswake** [notedit/media-server-go#56]
When creating WebRTC to RTMP server I am getting the following error:

fatal error: runtime.SetFinalizer: first argument is native.SwigcptrRTPIncomingSourceGroup, not pointer

goroutine 34 [running]:
runtime.throw(0xc000278480, 0x5a)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000395308 sp=0xc0003952d8 pc=0x4c2ed2
runtime.SetFinalizer(0xdc6280, 0xc0003a0b70, 0xcf75a0, 0xc000387580)
        /usr/local/go/src/runtime/mfinal.go:321 +0x7f0 fp=0xc0003953f0 sp=0xc000395308 pc=0x4af8b0
github.com/notedit/media-server-go.(*IncomingStream).CreateTrack(0xc00037e600, 0xc00037e500, 0xc000395710)
        /home/ben/go/src/github.com/notedit/media-server-go/incomingstream.go:284 +0x107c fp=0xc0003956e0 sp=0xc0003953f0 pc=0x9edecc
github.com/notedit/media-server-go.newIncomingStream(0xedba40, 0xc0003a03e0, 0xeccc80, 0xc0003a0b60, 0xc0003974a0, 0x0)
        /home/ben/go/src/github.com/notedit/media-server-go/incomingstream.go:47 +0x1d5 fp=0xc000395780 sp=0xc0003956e0 pc=0x9ec215
github.com/notedit/media-server-go.(*Transport).CreateIncomingStream(0xc0002f09a0, 0xc0003974a0, 0xc000395858)
        /home/ben/go/src/github.com/notedit/media-server-go/transport.go:481 +0xa4 fp=0xc0003957d0 sp=0xc000395780 pc=0x9fdbc4
main.channel(0xc000240680)
        /home/ben/go/src/github.com/benpeterswake/test/server.go:102 +0x3f6 fp=0xc000395918 sp=0xc0003957d0 pc=0xa01e26
github.com/gin-gonic/gin.(*Context).Next(0xc000240680)
        /home/ben/go/src/github.com/gin-gonic/gin/context.go:147 +0x3a fp=0xc000395930 sp=0xc000395918 pc=0x97861a
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc000240680)
        /home/ben/go/src/github.com/gin-gonic/gin/recovery.go:83 +0x5a fp=0xc000395960 sp=0xc000395930 pc=0x98c2aa
github.com/gin-gonic/gin.(*Context).Next(0xc000240680)
        /home/ben/go/src/github.com/gin-gonic/gin/context.go:147 +0x3a fp=0xc000395978 sp=0xc000395960 pc=0x97861a
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000240680)
        /home/ben/go/src/github.com/gin-gonic/gin/logger.go:241 +0xe1 fp=0xc000395b18 sp=0xc000395978 pc=0x98b3d1
github.com/gin-gonic/gin.(*Context).Next(0xc000240680)
        /home/ben/go/src/github.com/gin-gonic/gin/context.go:147 +0x3a fp=0xc000395b30 sp=0xc000395b18 pc=0x97861a
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0002b9040, 0xc000240680)
        /home/ben/go/src/github.com/gin-gonic/gin/gin.go:411 +0x66d fp=0xc000395cb8 sp=0xc000395b30 pc=0x9825dd
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0002b9040, 0xecad80, 0xc00029a2a0, 0xc00023e700)
        /home/ben/go/src/github.com/gin-gonic/gin/gin.go:369 +0x14e fp=0xc000395cf0 sp=0xc000395cb8 pc=0x981cde
net/http.serverHandler.ServeHTTP(0xc0002404e0, 0xecad80, 0xc00029a2a0, 0xc00023e700)
        /usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc000395d20 sp=0xc000395cf0 pc=0x750178
net/http.(*conn).serve(0xc00030c000, 0xecc680, 0xc000239880)
        /usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc000395fc8 sp=0xc000395d20 pc=0x74bd61
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000395fd0 sp=0xc000395fc8 pc=0x4ef1b1
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by benpeterswake** [comment]
i found a temporary fix. Just change at github.com/notedit/media-server-go/incomingstream.go:284 to pointer:

runtime.SetFinalizer(&source, func(source *native.RTPIncomingSourceGroup) {
				i.transport.RemoveIncomingSourceGroup(*source)
			})

**Comment by benpeterswake** [comment]
So i found a fix. All the runtime.SetFinalizer() calls need to be change to pointers. e.g.
runtime.SetFinalizer(&source, func(source *native.RTPIncomingSourceGroup) {
		t.transport.RemoveIncomingSourceGroup(*source)
	})

**Comment by notedit** [comment]
it is my fault.

**Comment by notedit** [comment]
try the  v0.1.17
