### ISSUE TITLE
WebRTC-RTMFP

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [notedit/media-server-go#74]
there is a nice project called libRTMFP
https://github.com/MonaSolutions/librtmfp
RTMFP is the UDP version of RTMP and much more packet loss tolerant allowing p2p and multicast streaming.
do you think this protocol can be integrated into media-server-go?

**Comment by al-sabr** [comment]
I think it is possible because there's already rtmfp implementation in golang. Search on GitHub you will find the code that can be copied and pasted.

**Comment by notedit** [comment]
No.
